name: sijilli
description: تطبيق مواعيد اجتماعي
publish_to: 'none'
version: 1.2.9+1026

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pocketbase: ^0.23.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.1
  image_picker: ^1.2.1
  just_audio: ^0.9.36
  file_picker: ^8.0.1
  image_cropper: ^11.0.0
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hijri: ^3.0.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  gal: ^2.3.2
  dio: ^5.9.0
  flutter_local_notifications: ^20.0.0
  timezone: ^0.10.1
  google_fonts: ^8.0.0
  adhan: ^2.0.0+1
  geolocator: ^14.0.2
  timeago: ^3.7.1
  device_calendar: ^4.3.2
  permission_handler: ^11.3.1
  fast_contacts: ^5.0.1
  pdf: ^3.10.8
  printing: ^5.11.1

  intl: ^0.20.2
  http: ^1.2.1
  flutter_web_plugins:
    sdk: flutter
  share_plus: ^12.0.2
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  device_info_plus: ^12.4.0
  crypto: ^3.0.7
  youtube_player_iframe: ^6.0.2
dependency_overrides:
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

  mocktail: ^1.0.4
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/logo/app_icon_new.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  image_path_android: "assets/logo/app_icon_new.png"
  image_path_ios: "assets/logo/app_icon_new.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/quran/quran.json
    - assets/fonts/NotoSansArabic-Regular.ttf
    - assets/fonts/Manal_High.ttf
    - assets/fonts/Manal_Bold.ttf

  fonts:
    - family: Manal_High
      fonts:
        - asset: assets/fonts/Manal_High.ttf
    - family: Manal_Bold
      fonts:
        - asset: assets/fonts/Manal_Bold.ttf
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf