-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgOeRPPyWmzA0ObENH
Km0lbAy1kDyUPmjrjXJw1H5rJgegCgYIKoZIzj0DAQehRANCAAQD4Tu6ziPItJM/
3VHwogk3xBYJUOfWp/gLdb57GKbrjBxV7R3TXZ5CKeqT3+sbTdrTQcFr8Si1ttam
t4WUTRhZ
-----END PRIVATE KEY-----